### ISSUE TITLE
MongoDB 업데이트

### ISSUE THREAD

**Issue by BasixKOR** [teamatus/openNAMU#11]
wiki.json을 지원 중지하고 MongoDB를 도입합시다.

**Comment by 2DU** [comment]
https://github.com/YJSoft/openRoot

**Comment by 2DU** [comment]
SQLite 라도 좋으니 패치점

**Comment by 2DU** [comment]
아니면 확 openRoot 기반으로 엎어버리는...

**Comment by 2DU** [comment]
음 진짜 오픈루트 기반으로 엎는것도 나쁘진 않겠다

**Comment by 2DU** [comment]
아냐 애초에 mariadb 쓸꺼면 미디어위키 쓰지 이거 왜 쓰겠어 기각

베이직은 빨리 일을 해서 MongoDB를 도입하라!

**Comment by 2DU** [comment]
음 바식스가 안보이니 그냥 내가 도입해보자 일단은 SQLite 기반으로 대충 해보자...

**Comment by 2DU** [comment]
DB는 너무 어려워서 끄적였더니 모니위키 구조식의 openNAMU를 만들었다... 완성도 높아지면 이걸로 확 엎어버리자 지금 보단 안정성 높으니

https://github.com/2DU/openNAMU/

**Comment by BasixKOR** [comment]
방금 커밋이 이겨 관련 커밋인데 실수로 번호 넣기 까먹엇네요

**Comment by 2DU** [comment]
노오력 하라

**Comment by 2DU** [comment]
deesle로 분리됨
