### ISSUE TITLE
구현 해야할 기능

### ISSUE THREAD

**Issue by 2DU** [teamatus/openNAMU#14]
## 대역 차단

덤: 말이 완료지 대다수 개선이 필요함

**Comment by closers-seulbi** [comment]
새로운 문서 추가 기능도 있어야 되지 않을까요?
지금은 닫혀있지만, 전에 문제를 뿜던 저의 웹에서는 문서 추가가 불가능했거든요

**Comment by 2DU** [comment]
제 경우엔 추가가 잘 되서...

**Comment by 2DU** [comment]
## 리비전 보기
### 되돌리기

**Comment by 2DU** [comment]
Fix

**Comment by 2DU** [comment]
문단 편집 제작중

**Comment by 2DU** [comment]
대역 차단 추가
