### ISSUE TITLE
오픈 나무 개선버전을 적용시켜봤습니다.

### ISSUE THREAD

**Issue by HyungJu** [teamatus/openNAMU#18]
개인적으로 수정한 버전입니다.
별로 바뀐건 아닙니다만 
* 멘트 수정
* 부트스트랩 일부적용
* 블라인드 처리 쉽게함
등 개선했습니당.. 
또 파서가 영 보기 힘들어서 파트별로 나눠서 처리하는 방식으로 바꾸는
작업도 진행중입니닷. 
완성되면 한꺼번에 이쪽에 PR넣을게영 
---> 프리뷰 ----> https://openwiki.herokuapp.com/w/FrontPage

**Comment by HyungJu** [comment]
heroku 이용하시는 분들 buildpack은 https://github.com/HyungJu/heroku-buildpack-nodejs 사용하심됩니당

**Comment by 2DU** [comment]
PR보다는 나중에 코드 완성하시면 올리고 이슈에 글 남겨주세요 최근 하루 단위로 계속 개선 중이라 수동 병합 해야할 듯 합니다.

**Comment by HyungJu** [comment]
네 알겠습니다
