### ISSUE TITLE
2DU님

### ISSUE THREAD

**Issue by HyungJu** [teamatus/openNAMU#22]
커밋은 계속하시는거보면 접속은 하시는것같은데 병합해주시면 감사하겠습니다.. 일부러 안받으시는건지 는 모르겠지만 안받으실거면 그냥 PR닫아주세요 제 개인 깃헙 계졍에 올리겠습니다

**Comment by 2DU** [comment]
아 죄송합니다;; 최근 깃허브 웹 킨 적이 없어서 지금 병합하죠
