### ISSUE TITLE
vi로 FrontPage.txt 직접 편집시 %0A가 붙음

### ISSUE THREAD

**Issue by Lastorder-DC** [teamatus/openNAMU#24]
`%0A`까지 문서명으로 인식해서 `문서명%0A` 페이지가 대문 페이지로 설정되는 문제점이 있습니다.

**Comment by 2DU** [comment]
[참조](https://github.com/teamatus/openNAMU/commit/1702bafd24c949db9f289b549ff348e309f3fd23)

마지막에 %0A가 붙으면 없애도록 했습니다
