### ISSUE TITLE
문서 이동 등 본문이 없는 편집에서 raw 클릭시 undefinded 오류

### ISSUE THREAD

**Issue by Lastorder-DC** [teamatus/openNAMU#25]
문서 이동 등 본문이 없는 편집에서 raw 클릭시 undefinded 오류가 발생합니다.

**Comment by 2DU** [comment]
[참조](https://github.com/teamatus/openNAMU/commit/6d09fa2f7706f77b0f26d18aadcd0e4be82f0acb)

리다이렉트 먹였습니다
