### ISSUE TITLE
의존성 목록 누락

### ISSUE THREAD

**Issue by LiteHell** [teamatus/openNAMU#33]
package.json에 의존성 목록 누락되어 있음.

**Comment by 2DU** [comment]
완료

**Comment by 2DU** [comment]
[참조](https://github.com/teamatus/openNAMU/commit/1576f30b5d29c6d4d1a60a70e37ac5b4af7704f3)

**Comment by LiteHell** [comment]
커밋에 메세지 남김. 확인 바람

**Comment by LiteHell** [comment]
하나 더 남김.

**Comment by 2DU** [comment]
확인함
