### ISSUE TITLE
node_modules 삭제

### ISSUE THREAD

**Issue by LiteHell** [teamatus/openNAMU#34]
그냥 `npm install`치면 의존성 목록에 있는 묘듈들 자동으로 싹 다 설치해주는 데 굳이 있어야 할 필요가 있나요? 삭제하고 `.gitignore` 파일에 `node_modules/` 추가하는 게 나을거 같은데.

**Comment by 2DU** [comment]
그러면 개발이 불편해짐

**Comment by ChalkPE** [comment]
1. 새로운 의존 패키지가 추가될 때마다 그 패키지에 있는 모든 파일들이 커밋에 포함됩니다.
    - `npm i` 커맨드 한 번이면 받을 수 있는데 굳이 커밋에 포함해서 데이터를 낭비하게 됩니다.
    - 남의 코드를 **마치 자기가 전부 작성한 것처럼** 직접 프로젝트에 집어넣는 건 문제가 있습니다.

2. npm 모듈을 사용하는 의미가 없습니다.
    - `package.json` 파일에 명시된 것과 `node_modules` 디렉터리의 상태가 서로 다를 수 있습니다.
    - 프로젝트를 처음부터 시작하는 입장에서는 `package.json`에 명시되지 않은 의존 패키지가 `node_modules` 디렉터리에 존재하게 되면 큰 혼란을 빚게 됩니다.
    - `node_modules` 디렉터리를 전부 프로젝트에 포함하면 굳이 `package.json`이 존재할 이유도 없습니다.

**Comment by ChalkPE** [comment]
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by 2DU** [comment]
허어... 그냥 했습니다
