### ISSUE TITLE
도움이 될듯하여

### ISSUE THREAD

**Issue by 2DU** [teamatus/openNAMU#7]
https://github.com/YJSoft/openRoot/releases/tag/0.1.0-alpha

어떤 사람이 본 엔진에다 php namumark와 mysql을 더한거라네요

**Comment by BasixKOR** [comment]
좋은 정보는 감사합니다만.. 이슈 트래커가 메신저 용도로 쓰이는게 아니라 말이죠. Close 해놓겟습니다. 일단 정보는 감사드려요!
