### ISSUE TITLE
디자인 개선

### ISSUE THREAD

**Issue by 2DU** [teamatus/openNAMU#9]
https://github.com/2DU/openNAMU/blob/master/primer.css
https://github.com/2DU/openNAMU/blob/master/edit.jade
https://github.com/2DU/openNAMU/blob/master/history.jade
https://github.com/2DU/openNAMU/blob/master/index.jade

패치 내용
![asdf](http://croatiabeta.herobo.com/wiki/lib/exe/fetch.php?t=1462340596&w=390&h=500&tok=17564d&media=%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7_2016-05-04_14.32.02.png)

568px 이하에서는 이렇게 됩니다

및 RAW 보기 메뉴 추가 및 취소선 회색, 무나키위 취소선 강조 기능 도입

**Comment by BasixKOR** [comment]
에... 원래 저렇게 나오는게 정상이에요 ㅇㅂㅇ... 디자인은 현재 엎기가 어려운 관계로 힘들 것 같아요!
raw 보기 메뉴는 추가하도록 하겟습니다

**Comment by 2DU** [comment]
어... 원래는 이렇게 나오는...
![???](http://croatiabeta.herobo.com/wiki/lib/exe/fetch.php?t=1462378240&w=320&h=480&tok=ea438a&media=%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7_2016-05-05_01.10.23.png)

**Comment by BasixKOR** [comment]
...언제 한번 부트스트랩으로 바꿔야겟네요.

**Comment by 2DU** [comment]
파이팅 ㅜㅜ

**Comment by 2DU** [comment]
일단 대충 해결 됬으니 긴그

**Comment by 2DU** [comment]
개선 완료
